### ISSUE TITLE
implement heredoc

### ISSUE THREAD

**Issue by VerinAntoine** [TheSecretOrganization/minishell#36]
Heredocs can be implemented in:
 * parsing
 * execution `Would need a new element type (TYPE_HEREDOC) with as value the delimiter from parsing`

**Comment by VerinAntoine** [comment]
@Neffi42 avis?

**Comment by Neffi42** [comment]
oui ca peut être bien

**Comment by Neffi42** [comment]
je prends le ticket @VerinAntoine

**Comment by VerinAntoine** [comment]
> oui ca peut être bien, ca sera a la place du infile du coup, @VerinAntoine ?

Si ça se fait dans le parsing non vu que le fichier ne devrait plus exister à ce moment, il faudrait transmettre de fd à la place

**Comment by Neffi42** [comment]
Ah ok je vois ce que tu veux dire,
Donc un type heredoc avec le délimiter
Et le type infile avec le fd sur le fichier unlink ?

**Comment by VerinAntoine** [comment]
soit dans le parsing et on passe le fd dans le type heredoc, soit dans l'exec et on passe le delimiter

**Comment by Neffi42** [comment]
pour moi le parsing ne fait que parser, le read ca releve plus de l'exec (je dis pas ca par flm 1er degre), ca me parait plus logique de passer le delimiter uniquement

**Comment by VerinAntoine** [comment]
totalement, je me posais juste la question
